approvals:
  # check will fail if there is no approval
  minimum: 4
  groups:
    # check will fail if there is not at least 1 approval
    # from backend persons
    backend:
      minimum: 1
      from:
        users:
          - yuichielectric
          - dchomh
    # check will fail if there is not at least 2 approval
    # from frontend persons
    frontend:
      minimum: 2
      from:
        users:
          - dchomh
          - rerwinx
